// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: pkg/srv/server/grpc/soi.proto

package soipb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// SoiData represents a SoiData
type SoiData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Hash          string      `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Uri           string      `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Tags          []string    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Rage          int32       `protobuf:"varint,6,opt,name=rage,proto3" json:"rage,omitempty"`
	NumViews      int32       `protobuf:"varint,7,opt,name=numViews,proto3" json:"numViews,omitempty"`
	NumReads      float32     `protobuf:"fixed32,8,opt,name=numReads,proto3" json:"numReads,omitempty"`
	Comprehension int32       `protobuf:"varint,9,opt,name=comprehension,proto3" json:"comprehension,omitempty"`
	CreatedAt     int64       `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UsageLog      []*UsageLog `protobuf:"bytes,11,rep,name=usageLog,proto3" json:"usageLog,omitempty"`
}

func (x *SoiData) Reset() {
	*x = SoiData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoiData) ProtoMessage() {}

func (x *SoiData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoiData.ProtoReflect.Descriptor instead.
func (*SoiData) Descriptor() ([]byte, []int) {
	return file_pkg_srv_server_grpc_soi_proto_rawDescGZIP(), []int{0}
}

func (x *SoiData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SoiData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SoiData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SoiData) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SoiData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SoiData) GetRage() int32 {
	if x != nil {
		return x.Rage
	}
	return 0
}

func (x *SoiData) GetNumViews() int32 {
	if x != nil {
		return x.NumViews
	}
	return 0
}

func (x *SoiData) GetNumReads() float32 {
	if x != nil {
		return x.NumReads
	}
	return 0
}

func (x *SoiData) GetComprehension() int32 {
	if x != nil {
		return x.Comprehension
	}
	return 0
}

func (x *SoiData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SoiData) GetUsageLog() []*UsageLog {
	if x != nil {
		return x.UsageLog
	}
	return nil
}

// UsageLog represents a usage log of SoiData
type UsageLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UsedAt int64  `protobuf:"varint,2,opt,name=usedAt,proto3" json:"usedAt,omitempty"`
}

func (x *UsageLog) Reset() {
	*x = UsageLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageLog) ProtoMessage() {}

func (x *UsageLog) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageLog.ProtoReflect.Descriptor instead.
func (*UsageLog) Descriptor() ([]byte, []int) {
	return file_pkg_srv_server_grpc_soi_proto_rawDescGZIP(), []int{1}
}

func (x *UsageLog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UsageLog) GetUsedAt() int64 {
	if x != nil {
		return x.UsedAt
	}
	return 0
}

//
type SoiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *SoiData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SoiRequest) Reset() {
	*x = SoiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoiRequest) ProtoMessage() {}

func (x *SoiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoiRequest.ProtoReflect.Descriptor instead.
func (*SoiRequest) Descriptor() ([]byte, []int) {
	return file_pkg_srv_server_grpc_soi_proto_rawDescGZIP(), []int{2}
}

func (x *SoiRequest) GetData() *SoiData {
	if x != nil {
		return x.Data
	}
	return nil
}

//
type SoiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SoiResponse) Reset() {
	*x = SoiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoiResponse) ProtoMessage() {}

func (x *SoiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_srv_server_grpc_soi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoiResponse.ProtoReflect.Descriptor instead.
func (*SoiResponse) Descriptor() ([]byte, []int) {
	return file_pkg_srv_server_grpc_soi_proto_rawDescGZIP(), []int{3}
}

func (x *SoiResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_pkg_srv_server_grpc_soi_proto protoreflect.FileDescriptor

var file_pkg_srv_server_grpc_soi_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x72, 0x76, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6f, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x73, 0x6f, 0x69, 0x22, 0xa8, 0x02, 0x0a, 0x07, 0x53, 0x6f, 0x69, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x73,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x75, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x6f, 0x69, 0x2e, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x08, 0x75, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x22,
	0x36, 0x0a, 0x08, 0x55, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2e, 0x0a, 0x0a, 0x53, 0x6f, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6f, 0x69, 0x2e, 0x53, 0x6f, 0x69, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x6f, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x40,
	0x0a, 0x0a, 0x53, 0x6f, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0b,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6f, 0x69, 0x12, 0x0f, 0x2e, 0x73, 0x6f,
	0x69, 0x2e, 0x53, 0x6f, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73,
	0x6f, 0x69, 0x2e, 0x53, 0x6f, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x73, 0x6f, 0x69, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_srv_server_grpc_soi_proto_rawDescOnce sync.Once
	file_pkg_srv_server_grpc_soi_proto_rawDescData = file_pkg_srv_server_grpc_soi_proto_rawDesc
)

func file_pkg_srv_server_grpc_soi_proto_rawDescGZIP() []byte {
	file_pkg_srv_server_grpc_soi_proto_rawDescOnce.Do(func() {
		file_pkg_srv_server_grpc_soi_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_srv_server_grpc_soi_proto_rawDescData)
	})
	return file_pkg_srv_server_grpc_soi_proto_rawDescData
}

var file_pkg_srv_server_grpc_soi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_srv_server_grpc_soi_proto_goTypes = []interface{}{
	(*SoiData)(nil),     // 0: soi.SoiData
	(*UsageLog)(nil),    // 1: soi.UsageLog
	(*SoiRequest)(nil),  // 2: soi.SoiRequest
	(*SoiResponse)(nil), // 3: soi.SoiResponse
}
var file_pkg_srv_server_grpc_soi_proto_depIdxs = []int32{
	1, // 0: soi.SoiData.usageLog:type_name -> soi.UsageLog
	0, // 1: soi.SoiRequest.data:type_name -> soi.SoiData
	2, // 2: soi.SoiService.RegisterSoi:input_type -> soi.SoiRequest
	3, // 3: soi.SoiService.RegisterSoi:output_type -> soi.SoiResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_srv_server_grpc_soi_proto_init() }
func file_pkg_srv_server_grpc_soi_proto_init() {
	if File_pkg_srv_server_grpc_soi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_srv_server_grpc_soi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoiData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_srv_server_grpc_soi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_srv_server_grpc_soi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_srv_server_grpc_soi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_srv_server_grpc_soi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_srv_server_grpc_soi_proto_goTypes,
		DependencyIndexes: file_pkg_srv_server_grpc_soi_proto_depIdxs,
		MessageInfos:      file_pkg_srv_server_grpc_soi_proto_msgTypes,
	}.Build()
	File_pkg_srv_server_grpc_soi_proto = out.File
	file_pkg_srv_server_grpc_soi_proto_rawDesc = nil
	file_pkg_srv_server_grpc_soi_proto_goTypes = nil
	file_pkg_srv_server_grpc_soi_proto_depIdxs = nil
}
