// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package soipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SoiServiceClient is the client API for SoiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoiServiceClient interface {
	RegisterSoi(ctx context.Context, in *SoiRequest, opts ...grpc.CallOption) (*SoiResponse, error)
}

type soiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoiServiceClient(cc grpc.ClientConnInterface) SoiServiceClient {
	return &soiServiceClient{cc}
}

func (c *soiServiceClient) RegisterSoi(ctx context.Context, in *SoiRequest, opts ...grpc.CallOption) (*SoiResponse, error) {
	out := new(SoiResponse)
	err := c.cc.Invoke(ctx, "/soi.SoiService/RegisterSoi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoiServiceServer is the server API for SoiService service.
// All implementations must embed UnimplementedSoiServiceServer
// for forward compatibility
type SoiServiceServer interface {
	RegisterSoi(context.Context, *SoiRequest) (*SoiResponse, error)
	mustEmbedUnimplementedSoiServiceServer()
}

// UnimplementedSoiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSoiServiceServer struct {
}

func (UnimplementedSoiServiceServer) RegisterSoi(context.Context, *SoiRequest) (*SoiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSoi not implemented")
}
func (UnimplementedSoiServiceServer) mustEmbedUnimplementedSoiServiceServer() {}

// UnsafeSoiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoiServiceServer will
// result in compilation errors.
type UnsafeSoiServiceServer interface {
	mustEmbedUnimplementedSoiServiceServer()
}

func RegisterSoiServiceServer(s grpc.ServiceRegistrar, srv SoiServiceServer) {
	s.RegisterService(&SoiService_ServiceDesc, srv)
}

func _SoiService_RegisterSoi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoiServiceServer).RegisterSoi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soi.SoiService/RegisterSoi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoiServiceServer).RegisterSoi(ctx, req.(*SoiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoiService_ServiceDesc is the grpc.ServiceDesc for SoiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soi.SoiService",
	HandlerType: (*SoiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSoi",
			Handler:    _SoiService_RegisterSoi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/srv/server/grpc/soi.proto",
}
