name: lint

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true
          cache-dependency-path: go.sum

      - name: os-version
        run: cat /etc/os-release

      - name: go-version
        run: go version

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: nofilter
          reporter: github-pr-review